name: one_of_serializer
description: Serializer for the one_of package
version: 1.3.0
homepage: https://github.com/Bdaya-Dev/dart-oneof

environment:
  sdk: '>=2.12.0 <3.0.0'


dependencies:
  one_of: ^1.3.0
  built_value: ^8.2.3

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
